

spring :
  datasource :
    url : jdbc:mysql://localhost:3306/lkm?characterEncoding=utf8&serverTimezone=UTC
    username : root
    password : 123456
    driverClassName : com.mysql.cj.jdbc.Driver
    platform: mysql
